# Generated by Django 5.2.1 on 2025-05-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(max_length=5000)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
