# Generated by Django 4.2.22 on 2025-06-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_createdate_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
